// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
// */
//const sidebars = {
//  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//
//  // But you can create a sidebar manually
//  tutorialSidebar: [
//    'intro',
//    'hello',
//    {
//      type: 'category',
//      label: 'Tutorial',
//      items: ['tutorial-basics/create-a-document'],
//    },
//  ],
//

const sidebars = {
networkSidebar: [
		{
			type: 'category',
			label: 'Networking',
			items: [
				'networks/overview',
				{
					type: 'category',
					label: 'Part 1 — Foundations',
					items: [
						'networks/history-of-networking',
						'networks/network-fundamentals',
						'networks/osi-model',
						'networks/tcpip-model',
						'networks/data-encapsulation',
						'networks/physical-layer-media',
						'networks/number-systems',
						'networks/network-devices-overview',
						'networks/standards-bodies',
					],
				},
				{
					type: 'category',
					label: 'Part 2 — Ethernet & Layer 2',
					items: [
						'networks/ethernet-fundamentals',
						'networks/mac-addressing',
						'networks/switching-fundamentals',
						'networks/vlans',
						'networks/stp',
						'networks/etherchannel',
						'networks/switch-security',
						'networks/layer2-troubleshooting',
						'networks/vxlan-and-modern-l2',
						'networks/wireless-layer2',
					],
				},
				{
					type: 'category',
					label: 'Part 3 — IP Addressing',
					items: [
						'networks/ipv4-fundamentals',
						'networks/ipv4-subnetting',
						'networks/ipv4-subnetting-practice',
						'networks/ipv6-fundamentals',
						'networks/ipv6-addressing-deep',
						'networks/ipv6-transition',
						'networks/dhcp',
						'networks/arp-and-ndp',
						'networks/nat-pat',
						'networks/dns',
					],
				},
				{
					type: 'category',
					label: 'Part 4 — Routing',
					items: [
						'networks/routing-fundamentals',
						'networks/static-routing',
						'networks/routing-protocols-overview',
						'networks/rip',
						'networks/ospf-fundamentals',
						'networks/ospf-advanced',
						'networks/eigrp',
						'networks/bgp-fundamentals',
						'networks/bgp-advanced',
						'networks/route-redistribution',
					],
				},
				{
					type: 'category',
					label: 'Part 5 — Transport & Application',
					items: [
						'networks/tcp-fundamentals',
						'networks/tcp-advanced',
						'networks/udp',
						'networks/http',
						'networks/tls-ssl',
						'networks/email-protocols',
						'networks/ftp-and-file-protocols',
						'networks/application-layer-reference',
					],
				},
				{
					type: 'category',
					label: 'Part 6 — WAN & Service Provider',
					items: [
						'networks/wan-technologies',
						'networks/mpls-deep',
						'networks/vpn-technologies',
						'networks/qos',
						'networks/multicast',
					],
				},
				{
					type: 'category',
					label: 'Part 7 — Network Security',
					items: [
						'networks/network-security-fundamentals',
						'networks/firewalls-and-ids',
						'networks/network-attacks',
						'networks/aaa-and-access-control',
						'networks/cryptography-for-networks',
						'networks/network-hardening',
					],
				},
				{
					type: 'category',
					label: 'Part 8 — Wireless',
					items: [
						'networks/wireless-fundamentals',
						'networks/wireless-security',
						'networks/wireless-architecture',
						'networks/wireless-troubleshooting',
					],
				},
				{
					type: 'category',
					label: 'Part 9 — Automation & SDN',
					items: [
						'networks/network-automation-fundamentals',
						'networks/ansible-for-networks',
						'networks/sdn-and-controllers',
						'networks/terraform-and-infrastructure-as-code',
						'networks/cloud-networking',
						'networks/network-telemetry',
					],
				},
				{
					type: 'category',
					label: 'Part 10 — Additional Topics',
					items: [
						'networks/containers-and-networking',
						'networks/troubleshooting-methodology',
						'networks/high-availability-and-redundancy',
						'networks/network-documentation-and-design',
					],
				},
				{
					type: 'category',
					label: 'Part 11 — Advanced Operations',
					items: [
						'networks/capacity-planning',
						'networks/service-provider-technologies',
						'networks/optical-networking',
					],
				},
				{
					type: 'category',
					label: 'Part 12 — Capstone & Reference',
					items: [
						'networks/ipv6-deployment-guide',
						'networks/network-protocols-quick-reference',
						'networks/cisco-ios-command-reference',
						'networks/capstone-network-design-scenario',
					],
				},
			],
		},
	],

	gitSidebar: [
		{
			type: 'category',
			label: 'Git & Version Control',
			items: [
				'git-versioncontrol/Introduction',
				'git-versioncontrol/GitFundamentals',
				'git-versioncontrol/Internals',
				'git-versioncontrol/Branching',
				'git-versioncontrol/Rebasing',
				'git-versioncontrol/Collaboration',
				'git-versioncontrol/Remotes',
				'git-versioncontrol/Workflows',
				'git-versioncontrol/Advanced',
				'git-versioncontrol/Git&DevOps',
				'git-versioncontrol/Commands',
				'git-versioncontrol/Flows',
			],
		},
	],
	linuxSidebar: [
		{
			type: 'category',
			label: 'Linux',
			items: [
				'linux/LinuxBasics',
				'linux/Filesystem',
				'linux/BasicCommands',
				'linux/Permissions',
				'linux/Packages',
				'linux/Users',
				'linux/Services',
				'linux/Networking',
				'linux/Logs',
				'linux/Maintenance',
				'linux/Troubleshooting',
				'linux/Security',
				'linux/Advanced'
			]
		}
	],
	javaSidebar: [
		{
			type: 'category',
			label: 'Java',
			items: [
				'Java/overview',
				'Java/java-fundamentals',
				'Java/java-oop',
				'Java/java-collections',
				'Java/java-streams',
				'Java/java-exceptions-io',
				'Java/java-concurrency',
				'Java/jakartaee-fundamentals',
				'Java/jpa-persistence',
				'Java/spring-core',
				'Java/spring-boot',
				'Java/spring-mvc-rest',
				'Java/spring-data-jpa',
				'Java/spring-security',
				'Java/spring-testing',
				'Java/spring-caching-events-transactions',
				'Java/spring-rest-clients',
				'Java/spring-production',
				'Java/modern-java',
				'Java/design-patterns'
			]
		}
	],
	javascriptSidebar: [
		{
			type: 'category',
			label: 'JavaScript',
			items: [
				'JavaScript/overview',
				'JavaScript/js-fundamentals',
				'JavaScript/js-arrays-objects',
				'JavaScript/js-functions-scope',
				'JavaScript/js-async',
				'JavaScript/js-classes-modules',
				'JavaScript/js-errors-regex',
				'JavaScript/js-dom-web-apis',
				'JavaScript/js-advanced-patterns',
				'JavaScript/js-browser-storage-apis',
				'JavaScript/js-number-date-math',
				'JavaScript/js-strings-advanced',
				'JavaScript/js-async-advanced',
				'JavaScript/nodejs-fundamentals',
				'JavaScript/nodejs-express',
				'JavaScript/nodejs-database',
				'JavaScript/nodejs-auth',
				'JavaScript/nodejs-testing',
				'JavaScript/nodejs-advanced',
				'JavaScript/nodejs-security-deployment',
				'JavaScript/bun',
				'JavaScript/angular-fundamentals',
				'JavaScript/angular-forms-http',
				'JavaScript/angular-state-rxjs',
				'JavaScript/angular-routing-advanced',
				'JavaScript/angular-testing',
				'JavaScript/vue-fundamentals',
				'JavaScript/vue-router-pinia',
				'JavaScript/vue-advanced',
				'JavaScript/vue-testing',
				'JavaScript/typescript',
				'JavaScript/tooling'
			]
		}
	],
	rustSidebar: [
		{
			type: 'category',
			label: 'Rust',
			items: [
				'Rust/overview',
				{
					type: 'category',
					label: 'Core Language',
					items: [
						'Rust/rust-fundamentals',
						'Rust/rust-basics',
						'Rust/rust-data-structures',
						'Rust/rust-ownership',
						'Rust/rust-structs-enums',
						'Rust/rust-traits-generics',
						'Rust/rust-error-handling',
						'Rust/rust-collections',
						'Rust/rust-lifetimes',
						'Rust/rust-closures-iterators',
						'Rust/rust-smart-pointers',
						'Rust/rust-modules',
						'Rust/rust-concurrency',
						'Rust/rust-async',
						'Rust/rust-testing',
					],
				},
				{
					type: 'category',
					label: 'Use Cases',
					items: [
						'Rust/rust-cli',
						'Rust/rust-web-api',
						'Rust/rust-systems',
						'Rust/rust-wasm',
					],
				},
				'Rust/rust-tooling',
			],
		},
	],
};


export default sidebars;
