// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
// */
//const sidebars = {
//  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//
//  // But you can create a sidebar manually
//  tutorialSidebar: [
//    'intro',
//    'hello',
//    {
//      type: 'category',
//      label: 'Tutorial',
//      items: ['tutorial-basics/create-a-document'],
//    },
//  ],
//

const sidebars = {
	networkSidebar: [
		{
			type: 'category',
			label: 'Network',
			items: [
				'networks/Introduction',
				'networks/Fundamentals',
				'networks/Switching&LANs',
				'networks/Routing',
				'networks/IPServices',
				'networks/Security',
			],
		},
	],

	gitSideba: [
		{
			type: 'category',
			label: 'Git & Version Control',
			items: [
				'git&versioncontrol/Introduction',
				'git&versioncontrol/GitFundamentals',
				'git&versioncontrol/Internals',
				'git&versioncontrol/Branching',
				'git&versioncontrol/Rebasing',
				'git&versioncontrol/Collaboration',
				'git&versioncontrol/Remotes',
				'git&versioncontrol/Workflows',
				'git&versioncontrol/Advanced',
				'git&versioncontrol/Git&DevOps',
				'git&versioncontrol/Commands',
			],
		},
	],
	linuxSidebar: [
		{
			type: 'category',
			label: 'Linux',
			items: [
				'linux/LinuxBasics',
				'linux/Filesystem',
				'linux/BasicCommands',
				'linux/Permissions',
				'linux/Packages',
				'linux/Users',
				'linux/Services',
				'linux/Networking',
				'linux/Logs',
				'linux/Maintenance',
				'linux/Troubleshooting',
				'linux/Security',
				'linux/Advanced'
			]
		}
	],
	javaSidebar: [
		{
			type: 'category',
			label: 'Java',
			items: [
				'Java/overview',
				'Java/java-fundamentals',
				'Java/java-oop',
				'Java/java-collections',
				'Java/java-streams',
				'Java/java-exceptions-io',
				'Java/java-concurrency',
				'Java/jakartaee-fundamentals',
				'Java/jpa-persistence',
				'Java/spring-core',
				'Java/spring-boot',
				'Java/spring-mvc-rest',
				'Java/spring-data-jpa',
				'Java/spring-security',
				'Java/spring-testing',
				'Java/spring-caching-events-transactions',
				'Java/spring-rest-clients',
				'Java/spring-production',
				'Java/modern-java',
				'Java/design-patterns'
			]
		}
	],
	javascriptSidebar: [
		{
			type: 'category',
			label: 'JavaScript',
			items: [
				'JavaScript/overview',
				'JavaScript/js-fundamentals',
				'JavaScript/js-arrays-objects',
				'JavaScript/js-functions-scope',
				'JavaScript/js-async',
				'JavaScript/js-classes-modules',
				'JavaScript/js-errors-regex',
				'JavaScript/js-dom-web-apis',
				'JavaScript/js-advanced-patterns',
				'JavaScript/js-browser-storage-apis',
				'JavaScript/js-number-date-math',
				'JavaScript/js-strings-advanced',
				'JavaScript/js-async-advanced',
				'JavaScript/nodejs-fundamentals',
				'JavaScript/nodejs-express',
				'JavaScript/nodejs-database',
				'JavaScript/nodejs-auth',
				'JavaScript/nodejs-testing',
				'JavaScript/nodejs-advanced',
				'JavaScript/nodejs-security-deployment',
				'JavaScript/bun',
				'JavaScript/angular-fundamentals',
				'JavaScript/angular-forms-http',
				'JavaScript/angular-state-rxjs',
				'JavaScript/angular-routing-advanced',
				'JavaScript/angular-testing',
				'JavaScript/vue-fundamentals',
				'JavaScript/vue-router-pinia',
				'JavaScript/vue-advanced',
				'JavaScript/vue-testing',
				'JavaScript/typescript',
				'JavaScript/tooling'
			]
		}
	],
};


export default sidebars;
